name: Run Automated Tests via Pytest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6 libnss3 libxss1 \
          fonts-liberation libappindicator3-1 libatk-bridge2.0-0 libgtk-3-0 \
          curl

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get -y install google-chrome-stable=118.0.5993.118-1


      - name: Install ChromeDriver
        run: pip install webdriver-manager selenium


      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager coverage ruff

      - name: Start Flask app
        run: |
          export FLASK_APP=app.py
          nohup python -m flask run --host=127.0.0.1 --port=9000 &

      - name: Wait for Flask to start
        run: |
          for i in {1..10}; do
            curl -s http://127.0.0.1:9000/ && break
            sleep 2
          done

      - name: Lint with Ruff
        run: ruff check .
        continue-on-error: true

      - name: Run tests with coverage
        run: coverage run -m pytest -v -s
